- name: using encrypted content
  hosts: servera
  vars_files:
# referefing files that are encrypted using ansible vault
    - token_file.yml
    - usermanegemnt.yml
  tasks:
    - name: trying to use sensitive info
      ansible.builtin.debug:
        msg: "{{ token }} of user {{ sat_user }}"
