- name: learning delegate to
  hosts: webservers
  vars:
    web_pkg: httpd
    web_svc: httpd
    web_doc_root: /var/www/html
  become: true
  tasks:
          - name: make sure web pkg is isntalled
            ansible.builtin.dnf:
                    name: "{{ web_pkg }}"
                    state: latest
          - name: start the webs erver
            ansible.builtin.service:
                    name: "{{ web_svc }}"
                    state: started
                    enabled: true
          - name: push web content
            ansible.builtin.copy:
                    src: index.html
                    dest: "{{ web_doc_root }}/index.html"
                    mode: 0644
          - name: allowing http thru firewall
            ansible.posix.firewalld:
              service: http
              permanent: true
              immediate: true
              state: enabled
          - name: checking for connectivity
            ansible.builtin.uri:
              url: "http://{{ ansible_facts['fqdn'] }}"
              status_code: 200
            become: false
            delegate_to: localhost
