- hosts: servera
  become: true
  vars:
    web_pkg: httpd
  roles:
    - name: websetup
  tasks:
    - name: task number 1
      shell: id
      notify:
        - sample handler
#    - name: running the role here
#      include_role:
#        name: websetup
    - name: task number 2
      shell: id
  handlers:
    - name: sample handler
      debug:
        msg: sample handler of task sectioned task
