- hosts: servera
  vars:
    acceptable_out: something
  tasks:
  - block:
    - ansible.builtin.script: lame_script.sh goo 
      register: out
      failed_when: acceptable_out in out.stdout_lines
    rescue:
    - debug:
        msg: "proof that rescue task ran"

#    - copy:
#        content: "{{ out }}"
#        dest: script_out
#    - fetch:
#        src: script_out
#        dest: .
#    - debug:
#        msg: task runnning on success condi
#      when: acceptable_out in out.stdout_lines
